### ISSUE TITLE
Findings and impressions extraction as well as training data

### ISSUE THREAD

**Issue by santosh9sanjeev** [ttumyche/UniXGen#4]
Firstly, I want to express my appreciation for the valuable insights your work has provided. 

Section Extraction:
In my attempt to replicate your results, I needed some clarification regarding the extraction of the "findings" and "impressions" sections from the report as they are not implemented in the repository. During training, I inadvertently used the entire report, and my train_loss reached approximately 4.92. However, I noticed that when I employed your "unixgen" model with a train_loss of only 4.39, the report generation was significantly better. I suspect that using the whole report might be causing this discrepancy. Could you kindly explain the process you used to extract the "findings" and "impressions" sections from the reports as some reports do not seem to have these sections explicitly named. I wanted to know whether these studies were excluded or some other mechanism was used to get the report data.

Training Data Count:
According to your paper, 204,102 studies were used for training. However, after excluding the LL views, I found that the number of unique study_ids amounted to 204,187, which slightly exceeds the mentioned count. I am curious if there might be something I am overlooking or if there is an explanation for this difference.

I apologize if these questions seem basic or repetitive, but your guidance and insights will be of immense help in improving my understanding and replicating your research effectively.

**Comment by ttumyche** [comment]
Thank you for reaching out to our paper :)

1. Section Extraction
For section extraction, you can refer to [the official repo of mimic-cxr](https://github.com/MIT-LCP/mimic-cxr/tree/master/txt).
The `create_section_files.py` will extract each section in the report.

2. Training Data Count
Due to the credential issue, we can not provide our preprocessed data.
However, we provide our [metadata](https://github.com/ttumyche/UniXGen/tree/main/metadata)  for train, valid and test split, including Dicom id, subject id, study id, view position, and number of CXR. 
After extracting each section of the report, you can configure the dataset according to the metadata.
Furthermore, we also use LL views. The lateral view contains both Lateral and LL views.
